### ISSUE TITLE
Camera Preview Stretched

### ISSUE THREAD

**Issue by akashmi** [davidgatti/dgCam#6]
Camera Preview Stretched on Few Android Devices.
and there are not any option for capture picture. (no any button for capture image)

**Comment by davidgatti** [comment]
@akashmi this is just an example where to learn from. Sadly the Android platform is to diverse :( If you would like to add support for more weird devices, fell free to create a pull request. 

For now the code is as is, and I don't plan to work on it. I'm also surprised that it still being used, and it works on modern devices :)
