### ISSUE TITLE
Portrait And LandScape Issue

### ISSUE THREAD

**Issue by anish-cynexis** [davidgatti/dgCam#9]
When I take portrait shot it converts that image into the landscape and if take landscape it converts to portrait. I have tried multiple solutions but not able to get exact, kindly help.

**Comment by davidgatti** [comment]
O man, I had no idea this project is till being used for anything :D This repo is so old I don't remember what is going on anymore, and I don't do Android development anymore. So I won't be able to help you out, sorry :(
